# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Create Release Folder
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' --exclude='gulpfile.js' --exclude='.npmignore' --exclude='scss/*' . ./release
    - name: Switch to Release Folder
      run: |
        cd release
        ls -la
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.39.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_VERSION: 0.0.0
        WITH_V: true
        REPO_OWNER: Unoblueboy
